### ISSUE TITLE
Pretrained model ?

### ISSUE THREAD

**Issue by onefish51** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#1]
Hi, Thanks for your work! It looks like very funny !
could you share your pre-trained model ? I want to test how nice it is ! I'm glad to see it !

**Comment by yxt132** [comment]
I am interested in getting it too! It will be great if the author could provide more detailed instruction on how to train the model using our own data.  

Thank you!

**Comment by xdhzhang1995** [comment]
Could you share your skinColor.pkl? I want to test the model with my data，Thank you!

**Comment by xd1073321804** [comment]
Hi, it's amazing in your work! I have finish skin detection with GMM and GDfilter. I really want to test it with my data for comparing. Could you shared you pre-trained model? Thanks a lot.

**Comment by molyswu** [comment]
Tied to pip install keras_segmentation  ,   python test .py      
File "test.py", line 18, in <module>
    from segmentation_models.backbones import get_preprocessing
ImportError: cannot import name 'get_preprocessing'
 keras==2.3.1
tensorflow==1.14.0
 Thanks

**Comment by molyswu** [comment]
pip install -U segmentation-models==0.2.1

ok

**Comment by xdhzhang1995** [comment]
Yes, you must install proper edtion.
But the author didn't share the pretrained model, we can't test the model.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"molyswu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 上午8:36
收件人:&nbsp;"JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation"<Face-skin-hair-segmentaiton-and-skin-color-evaluation@noreply.github.com&gt;;
抄送:&nbsp;"断了的纟戋"<1113280356@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation] Pretrained model ? (#1)




pip install -U segmentation-models==0.2.1
 
ok

**Comment by molyswu** [comment]
you must install proper edtion.
But the author didn't share the pretrained model, we can't test the model.

**Comment by JACKYLUO1991** [comment]
@onefish51 @yxt132 @xdhzhang1995 Thank you for your support. After the paper is published, I will disclose the detailed training steps.

**Comment by xd1073321804** [comment]
> @onefish51 @yxt132 @xdhzhang1995 Thank you for your support. After the paper is published, I will disclose the detailed training steps.

Ok, Thanks a lot

**Comment by JACKYLUO1991** [comment]
Replied.
