### ISSUE TITLE
Dataset for skin color classification

### ISSUE THREAD

**Issue by jigyasa27** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#10]
Can you please provide the link to the manually annotated face skin tone grading dataset.
I am working on a similar project and the dataset might be useful for me.
Thank You

**Comment by JACKYLUO1991** [comment]
@jigyasa27 Sorry, this job is done during my internship, copyright does not belong to individuals. However, you can find a data set of beauty scores online.
