### ISSUE TITLE
Backbone network used

### ISSUE THREAD

**Issue by Nerdyvedi** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#4]
Which backbone segmentation network is being used in each model(Trained with different datasets)?
Thanks

**Comment by JACKYLUO1991** [comment]
The backbone network used our own proposed 'HLNet' ...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vedanta Jha"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月1日(星期六) 凌晨4:11
收件人:&nbsp;"JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation"<Face-skin-hair-segmentaiton-and-skin-color-evaluation@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation] Backbone network used (#4)




Which backbone segmentation network is being used in each model(Trained with different datasets)?
 Thanks

**Comment by Nerdyvedi** [comment]
Oh, Okay. Why have you set the default for backbone as none then. Thanks

**Comment by Nerdyvedi** [comment]
@JACKYLUO1991 Have you not added the files for HLNet yet ? Sorry for disturbing you.

**Comment by JACKYLUO1991** [comment]
@Nerdyvedi Hello, the experiment is actually done long ago, and the HLNet (HLRNet is its early version) network in the paper has been updated recently. However, the paper is in the second review .. Once it is done, I will immediately announce all training details.

**Comment by Nerdyvedi** [comment]
@JACKYLUO1991 . Thank you so much.
I am training the HLNet network(from your last commit) and the HLRNet network with default parameters, Would the results be not as good as the paper claims ?

**Comment by JACKYLUO1991** [comment]
@Nerdyvedi Certainly.
