### ISSUE TITLE
CelebA数据集

### ISSUE THREAD

**Issue by Wangyf46** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#5]
你好：
        最近再阅读您的paper以及代码。能否将文章中提到的CelebA的子集3556张图片以及对应标签发送给我一份，我在网络上没有找到公开资源，谢谢。
       另外，您在文章中提到的手工标准的人脸肤色数据集是否考虑公开呢？

**Comment by JACKYLUO1991** [comment]
@Wangyf46 Please go to this URL: http://www.cs.ubbcluj.ro/~textasciitilde dadi/face-hair-segm-database.html

**Comment by JACKYLUO1991** [comment]
Please go to this URL: (http://www.cs.ubbcluj.ro/~textasciitilde dadi/face-hair-segm-database.html)

**Comment by JACKYLUO1991** [comment]
Please go to this URL: http://www.cs.ubbcluj.ro/~dadi/face-hair-segm-database.html

**Comment by JACKYLUO1991** [comment]
@Wangyf46 Please go to this URL: http://www.cs.ubbcluj.ro/~dadi/face-hair-segm-database.html.
