### ISSUE TITLE
labeled datasets

### ISSUE THREAD

**Issue by Echosanmao** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#6]
hello~
Thank you for sharing this wonderful work.
Just now, I'm reading your paper and i have a question that  how you labeled the datasets ? Or just used the method "via a super-pixel segmentation algorithm." mentioned in the LFW dataset' description?
In addition, could you offer me some suggtions about how to label the datasets?

**Comment by JACKYLUO1991** [comment]
LFW dataset has given the corresponding label format, you just need to convert it into the training format (0, 1, 2, ...... N; N is class number).

**Comment by JACKYLUO1991** [comment]
@Echosanmao LFW dataset has given the corresponding label format, you just need to convert it into the training format (0, 1, 2, ...... N; N is class number).
