### ISSUE TITLE
Dr. Luo, cannot contact you by email(lingluo@stu.neu.edu.cn)

### ISSUE THREAD

**Issue by JunHanStudy** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#7]
Dear Dr. Luo,
   I am working on a skin tone classification project and recently read your great project about it. Could I have a chat with you on weekends about some detail? Could I have your Wechat so that we have a chat on weekends when you are free? 
   Thanks! Appreciate if you could have time to reply back!
Best,
Jun
https://home.cs.dartmouth.edu/~junhan/

**Comment by JACKYLUO1991** [comment]
You can contact me by email: lingluo@stumail.neu.edu.cn.
