### ISSUE TITLE
pipline_test.py

### ISSUE THREAD

**Issue by Echosanmao** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#9]
hello~
Today I find that the path blow which was written in the pipline_test.py 
clf = joblib.load('./experiments/skinGrade/skinColor.pkl'), I just didn't find it, so I want to know
how did this .pkl file  generated?

**Comment by JACKYLUO1991** [comment]
@Echosanmao This is the weighted model after serialization, produced by the random forest classifier.

**Comment by Echosanmao** [comment]
OK.
When you test the LFW and Figaro1k datasets, you said you set margin=0.3 before, but in the paper the value of margin=0.8. So I want to know could I get the latest version of the paper if you have made major revisions to the paper?

**Comment by JACKYLUO1991** [comment]
@Echosanmao It's disgusting that this journal doesn't seem to like me to publish a preprinted version, and I can't revoke it.. 0.3 or 0.8 depends on your actual application scenario, such as whether the hair must be fully contained.

**Comment by Echosanmao** [comment]
I have a stupid question that I use model.evaluate() to get the test data' loss and four metric value, but I got the values were strange just like these:
loss, mean_iou, frequency_weighted_iou, mean_accuracy, pixel_accuracy=(1.8796906471252441, 0.2271881103515625, 0.6815643310546875, 0.3333333432674408, 0.6815643310546875)，
so I want to know have you use model.evaluate()?
